version: '3.7'

services:
  mqtt2http:
    build:
      context: mqtt2http
      dockerfile: Dockerfile
    container_name: mqtt2http
    restart: always
    env_file:
      - .env

  mqtt2logging:
    build:
      context: mqtt2logging
      dockerfile: Dockerfile
    container_name: mqtt2logging
    restart: always
    env_file:
      - .env
